github:
  description: "Nano: The official Apache CouchDB library for Node.js"
  homepage: https://www.npmjs.com/package/nano
  labels:
    - apache
    - couchdb
    - nano
    - nodejs
  protected_branches:
    main:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: true

